# Generated by Django 5.2.1 on 2025-06-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_content_review_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Shop',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='store',
            new_name='Shop',
        ),
    ]
