# Generated by Django 5.2.1 on 2025-06-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_store_shop_rename_store_product_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Shop',
            new_name='shop',
        ),
    ]
